# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-08 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170508_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name=b'isActive'),
        ),
    ]
