# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_allergen_contains_gluten'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='allergen_contains_gluten',
            new_name='gluten_free',
        ),
    ]
