# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170412_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name=b'Email')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name=b'Login')),
                ('password', models.CharField(max_length=255, verbose_name=b'Password')),
            ],
        ),
    ]
