# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-07 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, default=b'/static/images/znakZap.jpg', null=True, upload_to=b'product_images'),
        ),
    ]
