# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-07 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20170707_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(upload_to=b'category_images'),
        ),
    ]
